services:
  postgres-db:
    image: postgres:18
    container_name: my-postgres-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgroot:/var/lib/postgresql

volumes:
  pgroot:
